import { Navbar } from "@/components/Navbar";
import LenisScrollProvider from "@/providers/lenis-scroll";
import ReactQueryProvider from "@/providers/react-query";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap/dist/css/bootstrap.min.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { ThemeProvider } from "@/context/ThemeContext";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="bottom-right" richColors />

        <SessionProvider>
          <ThemeProvider>
            <ReactQueryProvider>
              <LenisScrollProvider>
                <div className="d-flex flex-column min-vh-100">
                  <Navbar />
                  <main className="flex-grow-1 container py-4">{children}</main>
                </div>
              </LenisScrollProvider>
            </ReactQueryProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
